[package]
name = "DeepLearning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
plotters = "^0.3.1"
itertools = "0.8.0"
ndarray-rand = "0.14.0"